# Generated by Django 5.0.1 on 2024-02-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_customuser_delete_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
